[package]
name = "ripgrep"
version = "14.1.1"
deps = ["pkg-config"]

[source]
type = "archive"
url = "https://github.com/BurntSushi/ripgrep/archive/14.1.1.tar.gz"
tag = ""

[build]
type = "auto"
args = []
output = "ripgrep"
